customCommands:
  - key: C
    description: "AI Commit (show message before commit)"
    context: files
    command: "sh -c 'aicommit2 --auto-select'"
    output: terminal
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
promptToReturnFromSubprocess: false
