
general.import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[font]
size = 12

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1

[scrolling]
history = 10000

[window]
decorations = "Buttonless"

[window.padding]
x = 0
y = 0

